#!/bin/sh

[ ! -d /opt ] && mkdir /opt
[ ! -d /opt/qemu ] && ln -s /var/packages/qemu4dsm/target/opt/qemu /opt/qemu
[ ! -f /lib/libpng16.so.16.20.0 ] && cp /var/packages/qemu4dsm/target/opt/qemu/lib/* /lib

exit 0