#!/bin/sh

# Package
PACKAGE="qemu4dsm"
# Others
INSTALL_DIR="/var/packages/${PACKAGE}"

start()
{
	echo "${PACKAGE} start"
}

stop()
{
	cd ${INSTALL_DIR}/target/ui/
	for f in run-*.sh; do
		echo "Stopping $f .."
		./$f stop
	done
#   sleep 30
#   for f in run-*.sh; do
#       ./$f status | grep running
#       ./$f force-stop
#   done
	echo "${PACKAGE} stop"	
}

case $1 in
	start)
		start
		exit 0
	;;
	stop)
		stop
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo "${INSTALL_DIR}/target/ui/api.log"
		exit 0
	;;
esac

exit 0